# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    container_name: batch_lecture_local
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=springbatch
      - MYSQL_USER=batch_user
      - MYSQL_PASSWORD=batch_user123
      - MYSQL_ROOT_PASSWORD=batch_user123
      - TZ=Asia/Seoul
